# Generated by Django 4.0.1 on 2022-02-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_postman'),
    ]

    operations = [
        migrations.AddField(
            model_name='postman',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_set', to='mainapp.post'),
        ),
    ]
