# Generated by Django 4.0.1 on 2022-02-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_post_liked_post_user_alter_postman_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postman',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='postman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.postman'),
        ),
    ]
