# Generated by Django 4.0.1 on 2022-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_post_user_remove_postman_post_post_postman'),
    ]

    operations = [
        migrations.AddField(
            model_name='postman',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postman',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
