# Generated by Django 4.0.1 on 2022-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_publisher_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(default='publisher title', max_length=200),
        ),
    ]
