# Generated by Django 4.0.1 on 2022-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_publisher_publisher_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
